### ISSUE TITLE
Cup Full Logic

### ISSUE THREAD

**Issue by Post404** [ThomDietrich/SenseoWifi#46]
Now that I added the full cup reminder automation I noticed that the full cup state isn't correct all the time.
I think the currect logic (correct me if i'm wrong) is that "Full cup" sets to true when brewing is done.
And "Full cup" goes to false when the cup is removed.
The logic for the brewing state is that it sets the state to brewing when brewing is started, waits untill heating is done and then changes state to ready.
If this is correct this means that if you remove the cup before brewing is finished (which happens almost every time), that the full cup status change will happen after removing the cup. That way there won't be a trigger to change that back to empty because the cup is allready gone.

I think it would be more usefull to set cup full to true when brewing is started, but only when there is a cup available, that way there is allways a cup to remove and set the state back to cup empty again.

**Comment by ThomDietrich** [comment]
Crazy! I never caught that :)

Your guess is right. This line sets the cup to be "full" after brewing, even though you could have taken the cup away in-between.

https://github.com/ThomDietrich/SenseoWifi/blob/bfe35350e810160e3195d59e1d38f4b9a968df4c/src/SenseoWifi.cpp#L161

I don't like moving the line to the beginning of the brew process. After all, it's not logical to claim the cup is full when it's certainly not ;)

I think one step to the solution is rather easy. We simply have to re-check whether a cup is actually available:

```
if (CupDetectorAvailableSetting.get() && myCup.isAvailable()) myCup.fillUp();
```

However, this doesn't solve the whole issue as you could have removed the cup in-between and added a new one right away... feels like we need a piece of additional logic to `mycup`, so that it is aware of it currently being filled. 

1. At beginning of the bew: Set `mycup.beingFilledUp()`
2. After the brew: Call `mycup.fillUp()` only of `mycup.isBeingFilledUp()`
3. When `mycup.cupAvailable` changes at any point, set the variable `mycup.beingFilledUp` to false

That should capture all cases I can think of. Let me know what you think.

**Comment by Post404** [comment]
I duplicated you automations to be able to automatically brew 1 cup and 2 cups.
I just tested the 1 cup automation and it didn't work.
It has to do with something a noticed earlier.
This is what happens on my end: Turn on Senseo > heating state > very shortly the brewing state> Ready state
That means that after heating, step 3 is triggered before step 2. So it is turned off before doing anything.
I changed the trigger of step 3 to this to fix is:
```
    trigger:
      platform: state
      entity_id: sensor.senseowifi_opstate
      from: "SENSEO_BREWING"
      for:
        hours: 0
        minutes: 0
        seconds: 0
        milliseconds: 500
```

I only tested this once but I thing 500 milliseconds should be more then enough.

**Comment by ThomDietrich** [comment]
Hey!
Great catch. I am not with my machine in the next few days and can't test. The trigger is "from: SENSEO_BREWING" - sounds like Home Assistant sees a state change that really shouldn't be there...
Imho we want this either fixed in the firmware or by doing something like:

```
      from: "SENSEO_BREWING"
      to:
        - "SENSEO_READY"
        - "SENSEO_NOWATER"
        - "SENSEO_OFF"
```
Seems overkill.
Could you capture every state change an see where this comes from? My approach would be to subscribe to the opstate topic with any MQTT client. If there is indeed a non-sensical state message, it should be removed from the firmware.

**Comment by ThomDietrich** [comment]
Hey, something still doesn't seem right:

![image](https://user-images.githubusercontent.com/2870104/140318926-dbbaba3c-31c8-47b7-bb13-b6784d3dcf82.png)

I am back home now and will explore where this could possibly come from. Best!

**Comment by ThomDietrich** [comment]
Silly me, it turned out to be exactly what you described in your second comment... which I read after going on a bug hunt myself :) I agree with your logic. I've changed the code to not fill a non existing cup, even when triggered manually on the machine. If the microcontroller doesn't know about a cup, it doesn't make sense to assume a filled cup.

----

Regarding your issue, I did take a look at how my machine behaves, but even after multiple tries I get a pretty clean picture, e.g.

![image](https://user-images.githubusercontent.com/2870104/140333857-e055ac06-bbde-489a-a5dc-e6abd1f80125.png)

I wonder if your LED timing is a bit different?

**Comment by Post404** [comment]
Thanks for all this!
My Senseo is just less powerful then.
It takes 1 min 21 sec to heat up.

i will also try out the changed automations.

**Comment by ThomDietrich** [comment]
I ran into another weird behavior just now:
![image](https://user-images.githubusercontent.com/2870104/140608436-32fff9a9-b066-4d03-9c46-213b6c8ab00c.png)
After leaving the machine in READY this happened after a while. Confused by the constant beeping I turned it off. I suspect this is related to the reheating that happens after a while.

**Comment by ThomDietrich** [comment]
About the reheating behavior. I didn't encounter it again. However, I also realized that I don't want the machine to even wait that long in the ready state. I've added a rule to turn the machine off after 10 minutes in SENSEO_READY. You can see that in the last block here:

![image](https://user-images.githubusercontent.com/2870104/140626356-574a7e80-1d0f-4d39-bb46-33b19298a401.png)

**Comment by Post404** [comment]
I think I see what is happening here. Your Senseo never really cools down because you are drinking so much coffee!
My Senseo is not in a cold place at all. It would take even longer if that was the case.
I've never used the brew-directly-after-heating logic, at least not knowingly by holding down the button.
If the only side effects is that it takes longer before it realises that it is brewing? If that is the case then I don't see a problem.

**Comment by ThomDietrich** [comment]
Hey @Post404 , I've just pushed updated numbers that should work for you and myself. Best!

Btw. the only issue is that the brew-directly-after-heating logic might detect the wrong coffee size now. Well well 🤷‍♂️

**Comment by Post404** [comment]
Thanks, I will apply the update! I think this can be closed

**Comment by ThomDietrich** [comment]
Still not 100% avoided 🤔 I did not expect this too be such a complicated issue ^^

![image](https://user-images.githubusercontent.com/2870104/141961489-4c67a6bd-baee-4d7b-b05d-d14b043ea89e.png)
